import TaurenMD.plots.predefined_configs as DEFS
from TaurenMD.plots.plot_param import plot_param as PP
from TaurenMD.plots.plot_param_series_single_subplot import plot_param_series_single_subplot as PPSSS
from TaurenMD.plots.plot_param_series_subplots import plot_param_series_subplots as PPSS